language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - "pip install nose"
  - "curl -s http://www.defunct.cc/maxmind-geoip-samples.tar.gz | tar -xzC tests/"
script: nosetests
